### PR TITLE
Integrate gtest and ctest

### PR DESCRIPTION
**Pull request by SgStapleton**

### CODE REVIEW

**Comment by kberryUSGS** [comment]
This isn't a very useful comment, but I looked at this and I have no idea why this isn't building on Travis on OSX. It looks like the cmake setup and .travis.yml here is virtually identical to what we used for CSM-CameraModel.

**Comment by jlaura** [comment]
Is this clang not using c++11?

**Comment by jlaura** [comment]
ehhh I see the CXX11 standard in the cmake lists. Another option might be how gtest is being pulled. Is the commit that came in as a submodule bleeding edge or a release?

**Comment by kberryUSGS** [comment]
@jlaura The pulling the bleeding edge of gtest was it! Pulling release-1.8.1 fixes this problem.

**Comment by kberryUSGS** [comment]
I wasn't sure of the best place to fix this, so I put in a separate PR with just the gtest submodule changes: PR #22

**Comment by SgStapleton** [comment]
So, it looks like travis failed to build for macos, but it is actually passing with @kberryUSGS 's changes (https://github.com/USGS-Astrogeology/eal/pull/12/checks?check_run_id=36105146).

**Comment by Kelvinrr** [comment]
Looks good :+1:

**Pull request merged**
